server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    # Set a larger client body size to accommodate file uploads (adjust as needed)
     client_max_body_size 100M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # ==========================================
    # Extract real client IP from trusted sources (Cloudflare and internal networks)
    # ==========================================
    # Cloudflare IP ranges (https://www.cloudflare.com/ips/)
    set_real_ip_from 10.0.0.0/8;
    set_real_ip_from 172.16.0.0/12;
    set_real_ip_from 192.168.0.0/16;
    
    # Use CF-Connecting-IP header set by Cloudflare to get the real client IP
    real_ip_header CF-Connecting-IP;
    # ==========================================

    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass g7_app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        
        # Set HTTPS parameter for Laravel to correctly identify secure requests (important for URL generation and redirects)
        #fastcgi_param HTTPS on;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
